### ISSUE TITLE
I have a problem with the Torus - can't render a smooth circle

### ISSUE THREAD

**Issue by JohanEkenstedt** [maxxfrazer/RealityGeometries#6]
I want to render a smooth Torus -but it looks like it is only possible to create 30-40 sides. 

This works - but gives corners (see attached image):

let torus = ModelEntity(mesh: try! .generateTorus(sides: 30, csSides: 3, radius: 3.99, csRadius: 0.03), materials: [SimpleMaterial(color: .blue, isMetallic: false)])

![IMG_F359F48B5C9F-1](https://user-images.githubusercontent.com/28659415/208388774-243c5425-8eaf-4a79-8d2d-83fd612f8d2e.jpeg)

Is there an upper limit of the number of sides that is resource constrained by the hard ware?

**Comment by maxxfrazer** [comment]
Hey, thanks for using this package @JohanEkenstedt!

I ran a quick test to make sure it's working, and by modifying this value I am able to get a smoother circle (click each image to enlarge):

| 32  |  64  | 128 |
|------|-------|------|
| ![torus_32](https://user-images.githubusercontent.com/5754073/208411298-86e1dcaf-7030-4888-8401-61a17ae17048.png) | ![torus_64](https://user-images.githubusercontent.com/5754073/208411297-ef713b4a-8308-402d-89a0-341557920f8f.png) | ![torus_128](https://user-images.githubusercontent.com/5754073/208411293-c7d47dd5-95da-4465-84bf-f528ce280247.png) |

The code used for each mesh creation is:

```swift
newMesh = try! MeshResource.generateTorus(sides: <#Segment Value#>, csSides: 32, radius: 0.3, csRadius: 0.03)
```

Where the segment value is 32, 64 or 128 depending on the table above. There's no hardcoded upper limit of this value, but is better to keep it as low as you can to keep generation and rendering expense to a minimum.

**Comment by JohanEkenstedt** [comment]
Thanks for the fast reply. It worked very well.
